### ISSUE TITLE
Kan niet inloggen

### ISSUE THREAD

**Issue by QkeleQ10** [mamorgen/magiscore#9]
Helaas, inloggen werkt ook op Magiscore niet meer.

**Comment by Netlob** [comment]
Waar probeer je in te loggen? De site of de app? De site is namelijk dood

**Comment by QkeleQ10** [comment]
Gecondoleerd

**Comment by QkeleQ10** [comment]
Haha sorry grapje. Ik heb de app geïnstalleerd (op Android) en het werkt super! Een kleine tip: Als ik de cijfers hersynchroniseer, is de animatie erg traag en het voelt een beetje buggy.

**Comment by Netlob** [comment]
Heb je dan misschien een schermopname? Bij mij loopt alles smooth (en zie ik niet eens een animatie haha)
